on load:
  set {ultimate_anahtar} to "&6Ultimate Anahtarı"
  set {sag_tık} to "&7Bu kutuyu açabilmek için kendi anahtarıyla sağ tıkla."
  set {ultimate_kasaacılım} to "&8&l» &bUltimate Kutusu"
  set {envantere_geldi_ultimate} to "&6Ultimate &7anahtarı envanterine eklendi."
  set {genel_izinyok} to "&7Bu komutu kullanmak için iznin yok."
  set {ulti_kutuacma} to "&a{OYUNCU} &7kişisi &6Ultimate &7kutusunu açıyor.."
  set {kutu_broadcast} to "&a{OYUNCU} &7kişisi {KUTU} kutusunu açarak {EŞYA} kazandı."
  set {yerin_yok} to "&7Bu kutuyu açabilmek için yeterli yerin yok."
